services:
  # Backend service
  - type: web
    name: umbc-lost-found-2-backend
    env: python
    buildCommand: cd lost-and-found/backend && pip install -r requirements.txt
    startCommand: cd lost-and-found/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend service
  - type: web
    name: umbc-lost-found-1
    env: node
    buildCommand: |
      cd lost-and-found && 
      npm install && 
      npm install react-qr-code@2.0.15 html5-qrcode@2.3.8 @mui/material @mui/icons-material @emotion/react @emotion/styled --force && 
      npm run build
    startCommand: cd lost-and-found && npm install -g serve && serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
