"""add firebase_uid to user model

Revision ID: b583f99ad0f0
Revises: 4e49c182649d
Create Date: 2025-03-27 01:25:01.276422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b583f99ad0f0'
down_revision: Union[str, None] = '4e49c182649d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
